config/routes.rb
Rails.application.routes.draw do
  resources :motors

  resources :welcome
  
  get 'welcome/index'

  resources :articles do
  	resources :comments

  end

  resources :tables

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/absen.rb
class Absen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :nama, presence: true, length: {minimum: 5}


	# validates :nama, presence: true,
	# length: { minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/motor.rb
class Motor < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "rian", password: "rian", 
	except: [:index, :show]	

	def index
		@articles = Article.all.order('nama ASC')
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
 
	end

	def edit 
		@article = Article.find(params[:id])
		
	end

	def create
		@article = Article.new(article_params)

		if @article.save
		redirect_to @article
		else
		render 'new'
			
		end
	
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
			
		end
		
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:nama, :email, :telepon, :alamat, :hobi)
			
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "rian", password:
	"rian", only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@commen = @article.comments.create(comment_params)
		redirect_to article_path(@article)
		
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy 
		redirect_to article_path(@article)
		
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
			
		end

end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: [:show, :edit, :update, :destroy]

  # GET /motors
  # GET /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1
  # GET /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors
  # POST /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to @motor, notice: 'Motor was successfully created.' }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1
  # PATCH/PUT /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to @motor, notice: 'Motor was successfully updated.' }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1
  # DELETE /motors/1.json
  def destroy
    @motor.destroy
    respond_to do |format|
      format.html { redirect_to motors_url, notice: 'Motor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motor_params
      params.require(:motor).permit(:nama, :email, :telepon, :alamat)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlees_helper.rb
module ArticleesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/helpers/table_helper.rb
module TableHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Form Edit</h1>
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p>
 
  <p>
    <%= form.label :telepon %><br>
    <%= form.text_area :telepon %>
  </p>

  <p>
    <%= form.label :alamat %><br>
    <%= form.text_area :alamat %>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1><center>Daftar Hadir</center></h1>

<a href= "/articles/new" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Absen Dulu !</a><br><br>

<div class="row">
  <div class="col-md-6 col-sm-6">
    <table class="table table-striped table-bordered table-responsive ">
      <thead class="table-dark" >
      <tr align="center">
        <th>No</th>
        <th>Nama</th>
        <th>Email</th>
        <th>Telepon</th>
        <th>Alamat</th>
        <th>Hobi</th>
        <th colspan="2">Action </th>
        
      </tr>
      </thead>
     
      <% @articles.each_with_index do |article, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= article.nama %></td>
          <td><%= article.email %></td>
          <td><%= article.telepon %></td>
          <td><%= article.alamat %></td>
          <td><%= article.hobi %></td>

          <td><%= link_to 'Show', article_path(article) %></td>
          <!-- <td><%= link_to 'Edit', edit_article_path(article) %></td> -->
          <td><%= link_to 'Hapus', article_path(article), method: :delete, 
            data: { confirm: 'Anda Yakin?'} %> </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-6 col-sm-6">
    
    <%= image_tag("aaas.jpeg", class: "img-fluid img-responsive") %>

  </div>
</div> 

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
	
	 <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= form.label :nama %> <br>
		<%= form.text_field :nama %>
	</p>

	<p>
		<%= form.label :email %><br>
		<%= form.text_field :email %>
	</p>

	<p>
		<%= form.label :telepon %><br>
		<%= form.text_field :telepon %>
	</p>

	<p>
		<%= form.label :alamat %><br>
		<%= form.text_field :alamat %>
	</p>

	<p>
		<%= form.label :hobi%><br>
		<%= form.text_area :hobi %>
	</p>

	<p>
		<%= form.submit %>
	</p>

	<% end -%>

	<%= link_to 'Daftar Hadir', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>nama</strong>
	<%= @article.nama %>
</p>

<p>
	<strong>email</strong>
	<%= @article.email %>
</p>

<p>
	<strong>telepon</strong>
	<%= @article.telepon %>
</p>

<p>
	<strong>alamat</strong>
	<%= @article.alamat %>
</p>

<p>
	<strong>hobi</strong>
	<%= @article.hobi %>
</p>
	<h2>Comments</h2>
	<%= render @article.comments %>
	
	<h2>Tambahkan Komentar: </h2>
	<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path(@article)%>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Hapus Komentar', [comment.article, comment], method: :delete, data: {confirm: 'Anda Yakin ?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], local: true) do |form| %>
	<p>
		<%= form.label :commenter %><br>
		<%= form.text_field :commenter %>

	</p>

	<p>
		<%= form.label :body %><br>
		<%= form.text_area :body %>
	</p>

	<p>
		<%= form.submit :komentari %>
	</p>

<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tugas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/motors/_form.html.erb
<%= form_with(model: motor, local: true) do |form| %>
  <% if motor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
      <% motor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telepon %><br>
    <%= form.text_field :telepon %>
  </div>

  <div>
    <%= form.label :alamat %><br>
    <%= form.text_area :alamat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/motors/edit.html.erb
<h1>Editing Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Show', @motor %> |
<%= link_to 'Back', motors_path %>

app/views/motors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motors</h1>

<div class="row">
  <div class="">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Nama</th>
          <th>Email</th>
          <th>Telepon</th>
          <th>Alamat</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @motors.each do |motor| %>
          <tr>
            <td><%= motor.nama %></td>
            <td><%= motor.email %></td>
            <td><%= motor.telepon %></td>
            <td><%= motor.alamat %></td>
            <td><%= link_to 'Show', motor %></td>
            <td><%= link_to 'Edit', edit_motor_path(motor) %></td>
            <td><%= link_to 'Destroy', motor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Motor', new_motor_path %>

app/views/motors/new.html.erb
<h1>New Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Back', motors_path %>

app/views/motors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @motor.nama %>
</p>

<p>
  <strong>Email:</strong>
  <%= @motor.email %>
</p>

<p>
	<strong>Telepon:</strong>
	<%= @motor.telepon %>
</p>

<p>
	<strong>Alamat:</strong>
	<%= @motor.alamat %>
</p>

<%= link_to 'Edit', edit_motor_path(@motor) %> |
<%= link_to 'Back', motors_path %>

app/views/tables/new.html.erb
<h1>Hallo</h1>

app/views/welcome/index.html.erb
<h1>Selamat Datang di Welcome</h1>
<%= link_to 'Lihat Daftar Hadir', controller: 'articles' %><br>
<a href="/articles" class="btn btn-primary" role="Button" aria-pressed="true">Daftar Hadir</a>